### ISSUE TITLE
support for hdr/exr/ktx2/dds/tga/qoi

### ISSUE THREAD

**Issue by AllenDang** [Roughsketch/imagesize#24]
This crate is super useful! I'm creating a image viewer, and might need those formats, I'll create a PR to help, :)

- [x] HDR
- [x] exr
- [x] ktx2
- [x] dds
- [x] tga
- [x] qoi

**Comment by AllenDang** [comment]
It's done, pls review the PR

**Comment by Roughsketch** [comment]
Quick update:

I've gone through and tidied up several of the implementations from the PR, most important of which was making TGA not have so many false positive. I actually had an instance during all this were it was detecting certain HEIF files as TGA so that's no longer happening now.

If you want to look over the implementation it's [here](https://github.com/Roughsketch/imagesize/blob/master/src/formats/tga.rs#L45). Basically just the corroborating checks I mentioned in the initial PR.

Going to fuzz over this and then I'll likely release v0.12 later tonight.

**Comment by Roughsketch** [comment]
Sorry for this but I think I'm going to delay it a bit longer. I started working on PNM support (#14) and it's like 99% done, just need to handle the no newline case. Want to avoid releasing 0.12 and then having to minor bump immediately after due to another forward facing API change.

**Comment by Roughsketch** [comment]
[0.12.0](https://github.com/Roughsketch/imagesize/releases/tag/v0.12.0) is released now, so going to close this. Thanks again!
